YacGroup/yacguide

app/src/main/java/com/example/paetz/yacguide/MainActivity.java
app/src/main/java/com/example/paetz/yacguide/RouteActivity.java
app/src/main/java/com/example/paetz/yacguide/TourbookActivity.java
app/src/main/java/com/example/paetz/yacguide/database/Ascend.java
app/src/main/java/com/example/paetz/yacguide/network/RockParser.java
app/src/main/java/com/example/paetz/yacguide/utils/AscendTypes.java
app/src/main/java/com/example/paetz/yacguide/utils/IntentConstants.java
app/src/main/java/com/example/paetz/yacguide/utils/WidgetUtils.java
app/src/main/res/layout/activity_main.xml

The tour book also allows additional ascend styles for looking at and wanting to climb routes.

Add missing ascend types

---

app/src/main/java/com/example/paetz/yacguide/RouteActivity.java
app/src/main/res/layout/activity_route.xml

The location data provided by the database can be used to create an
Map intent and show the summit in a user defined mapping
application (e.g. OsmAnd, Google Maps).
Signed-off-by: Fabian Kantereit <fabian.kantereit@tsaro.io>

Implement simple maps support

---

app/build.gradle
app/src/main/java/com/example/paetz/yacguide/MainActivity.kt
app/src/main/res/layout/activity_main.xml

Derive app version from Git repo and show app version in main menu

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Update gradle version

---

LICENSE

This should only be merged, if every contributor approves.
Closes #69

License the code under LGPL

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/yacgroup/yacguide/AboutActivity.kt
app/src/main/java/com/yacgroup/yacguide/BaseNavigationActivity.kt
app/src/main/res/layout/activity_about.xml
app/src/main/res/layout/app_bar_about.xml
app/src/main/res/layout/content_about.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/menu/main.xml
app/src/main/res/values/strings.xml

The app versioning is up for discussion (see change in `build.gradle`):
- Do we need versioning at all?
- Do we want manual or automated versioning?
- What does Fdroid need in that regard?
- How will our "release" process look like? I believe, the easiest approach for us would be: merge to master -> CI builds apk -> new build is immediately published on Fdroid as the only available artifact. I guess, in that case, an increasing build number makes most sense instead of a version number.

Added About view

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/TableActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/AppDatabase.kt
app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Route.kt
app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
app/src/main/java/com/yacgroup/yacguide/database/TourbookExporter.kt
app/src/main/java/com/yacgroup/yacguide/network/RockParser.kt
app/src/main/java/com/yacgroup/yacguide/utils/AscendStyle.kt
app/src/main/java/com/yacgroup/yacguide/utils/CustomSettings.kt
app/src/main/res/layout/content_tourbook.xml
app/src/main/res/values/strings.xml

add ascend counters to summit and route tables

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/AppDatabase.kt
app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Route.kt
app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
app/src/main/java/com/yacgroup/yacguide/database/TourbookExporter.kt
app/src/main/java/com/yacgroup/yacguide/network/RockParser.kt
app/src/main/java/com/yacgroup/yacguide/utils/AscendStyle.kt
app/src/main/res/values/strings.xml

Resolves #101 
Note: 
- Database structure update was necessary
- the eye symbol is unfortunately utf-16 and since we use utf-8 throughout the code base, I used a finger symbol

Show finger if watched ascend available

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookAscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/AppDatabase.kt
app/src/main/java/com/yacgroup/yacguide/database/AscendDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Route.kt
app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
app/src/main/java/com/yacgroup/yacguide/database/TourbookExporter.kt
app/src/main/java/com/yacgroup/yacguide/network/RockParser.kt
app/src/main/java/com/yacgroup/yacguide/utils/AscendStyle.kt
app/src/main/res/values/strings.xml

Resolves #110. Hopefully last structural DB update.

Consolidated ascend counts to bit mask in db

---

app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt

Fix app crash if tourbook is empty

---

app/src/main/java/com/yacgroup/yacguide/database/AppDatabase.kt

Fix reset of rock and route ascends bit mask while tourbook import

---

CONTRIBUTING.md
Makefile
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/yacgroup/yacguide/AboutActivity.kt
app/src/main/java/com/yacgroup/yacguide/PrivacyPolicyActivity.kt
app/src/main/res/layout/content_about.xml
app/src/main/res/layout/content_privacy_policy.xml
app/src/main/res/raw/privacy_policy.md
app/src/main/res/values/strings.xml
docs/.gitignore
docs/Gemfile
docs/Gemfile.lock
docs/_config.yml
docs/index.md
docs/privacy_policy.md

Fix #124. As soon as this PR is merged, I will enable the GitHub page which then will be available under <https://yacgroup.github.io/yacguide>.

Add privacy policy

---

app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
app/src/main/java/com/yacgroup/yacguide/database/Route.kt
app/src/main/res/layout/content_preferences.xml
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Added configurable rock counting

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/res/layout/searchbar_rock.xml
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml

Store only-summits-check in shared preferences

---

app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookAscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/AppDatabase.kt
app/src/main/java/com/yacgroup/yacguide/database/AscendDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Comment/RegionCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Comment/RockCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Comment/RouteCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Comment/SectorCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/database/CountryDao.kt
app/src/main/java/com/yacgroup/yacguide/database/PartnerDao.kt
app/src/main/java/com/yacgroup/yacguide/database/RegionDao.kt
app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
app/src/main/java/com/yacgroup/yacguide/database/SectorDao.kt
app/src/main/java/com/yacgroup/yacguide/database/TourbookExporter.kt
app/src/main/java/com/yacgroup/yacguide/network/RockParser.kt
app/src/main/res/values/strings.xml

This PR is a requirement for #131 .
Although List type may be slower due to dynamically allocated memory, I don't expect a huge impact on runtime since db interaction remains the bottleneck.

changed db interface from array to list

---

app/src/main/java/com/yacgroup/yacguide/UpdatableTableActivity.kt
app/src/main/res/values/strings.xml

Removed are-u-sure dialog on updating db

---

app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/UpdatableTableActivity.kt
app/src/main/res/layout/button_download.xml

Added download button if country or region is empty

---

app/src/main/java/com/yacgroup/yacguide/AboutActivity.kt
app/src/main/res/layout/content_about.xml
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml

Add license view

---

app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
app/src/main/res/layout/content_preferences.xml
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml

Added new rock status Collapsed

---

app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt

re-arranged type-of-climbing widget in description activity

---

app/src/main/java/com/yacgroup/yacguide/utils/NetworkUtils.kt

Fix URL encoding

---

app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt
app/src/main/java/com/yacgroup/yacguide/utils/ParserUtils.kt
app/src/main/java/com/yacgroup/yacguide/utils/WidgetUtils.kt

Added czech names to sectors, rocks, routes

---

app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt

Preserve current year on pausing tourbook activity

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt

Initialize DatePicker with ascends date if available

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/Ascend.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Route.kt
app/src/main/res/layout/searchbar_rock.xml
app/src/main/res/values/strings.xml

Added checkbox for displaying only projected rocks in RockActivity

---

app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/AppDatabase.kt
app/src/main/java/com/yacgroup/yacguide/database/Ascend.kt
app/src/main/java/com/yacgroup/yacguide/database/AscendDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Country.kt
app/src/main/java/com/yacgroup/yacguide/database/CountryDao.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/Partner.kt
app/src/main/java/com/yacgroup/yacguide/database/PartnerDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Region.kt
app/src/main/java/com/yacgroup/yacguide/database/RegionDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Route.kt
app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
app/src/main/java/com/yacgroup/yacguide/database/Sector.kt
app/src/main/java/com/yacgroup/yacguide/database/SectorDao.kt
app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RegionComment.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RegionCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RockComment.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RockCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RouteComment.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RouteCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/SectorComment.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/SectorCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

Resolves #191 .
This PR makes sql requests in the database much handier und easier to read.

Clean-up of sql commands

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/res/drawable/spinner_shape.xml
app/src/main/res/layout/activity_rock.xml
app/src/main/res/layout/searchbar.xml
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml

Introduced filter spinner for RockActivity

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt
app/src/main/res/layout/activity_ascend.xml
app/src/main/res/layout/spinner_item.xml
app/src/main/res/values/strings.xml

* Use full screen width, which improves usability of note text field
* Make complete view scrollable, so that note text field can adapt to its content
* Make font of spinner items equal to the rest

Optimize ascend edit layout

---

app/src/main/java/com/yacgroup/yacguide/AboutActivity.kt
app/src/main/res/layout/about_entry.xml
app/src/main/res/layout/activity_about.xml
app/src/main/res/layout/content_about.xml
app/src/main/res/values/strings.xml

Fixes #156 
* Use default background (white)
* Left align items
* Make items with URLs clickable

Rework of about view

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt

Fix missing initialization of partner IDs

---

app/src/main/java/com/yacgroup/yacguide/AboutActivity.kt
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml

Add email contact to about view

---

app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Update gradle and libraries

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/TableActivity.kt
app/src/main/res/values/strings.xml

Fixed re-request of rocks after entering ascend

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/yacgroup/yacguide/AboutActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/utils/ActivityUtils.kt
app/src/main/java/com/yacgroup/yacguide/utils/ContactUtils.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/file_paths.xml

Implement bug reporting via email

---

app/src/main/java/com/yacgroup/yacguide/utils/ContactUtils.kt
app/src/main/res/values/strings.xml

This improves the implementation made in #210.

Filter out non-email apps when opening an email intent

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/TableActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/res/values/strings.xml

Added botch filter to rock table

---

app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/res/layout/nav_tourbook.xml
app/src/main/res/layout/numberpicker.xml
app/src/main/res/values/strings.xml

Added number picker for year selection in tourbook (#179)

---

app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/res/layout/add_partner_dialog.xml
app/src/main/res/values/strings.xml

Fix disappearing partner selection, if search field is used

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt

Fix broken ascend update

---

app/src/main/res/layout/searchbar.xml

Fixed automatic search field focus in rock table

---

app/src/main/java/com/yacgroup/yacguide/AboutActivity.kt
app/src/main/java/com/yacgroup/yacguide/DialogWidgetBuilder.kt
app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/TableActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookAscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/UpdatableTableActivity.kt
app/src/main/java/com/yacgroup/yacguide/WhatsNewInfo.kt
app/src/main/java/com/yacgroup/yacguide/utils/DialogWidgetBuilder.kt

Make all dialogs non-cancelable

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt

Fixed partner update on resuming from PartnersActivity by phone's back button

---

app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/res/layout/choose_tourbook.xml
app/src/main/res/values/strings.xml

Removed projects tab from tourbook view

---

app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

Add username to comment

---

app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt

Add project and botch filter to route view

---

app/build.gradle
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookEntryVerbose.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookExportFormat.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookExporter.kt
app/src/main/java/com/yacgroup/yacguide/utils/IntentConstants.kt
app/src/main/res/values/strings.xml

Pretty print for tour book export

---

app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/UpdateHandler.kt
app/src/main/java/com/yacgroup/yacguide/UpdateListener.kt
app/src/main/java/com/yacgroup/yacguide/database/Country.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/CountryViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/network/CountryParser.kt
app/src/main/res/layout/activity_country.xml
app/src/main/res/layout/activity_sector.xml
app/src/main/res/layout/activity_table.xml
app/src/main/res/layout/button_download.xml
app/src/main/res/layout/content_table.xml
app/src/main/res/layout/list_data_item.xml
app/src/main/res/layout/list_view_content.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Migrated country list to recycler view

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt
app/src/main/res/drawable/ic_start.xml
app/src/main/res/layout/activity_launch.xml

Added start-up activity

---

app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/Region.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RegionViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/network/RegionParser.kt
app/src/main/res/layout/activity_region_manager.xml
app/src/main/res/layout/activity_table.xml

Migrated region list to recycler view

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/Rock.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RockViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt
app/src/main/java/com/yacgroup/yacguide/utils/AscendStyle.kt
app/src/main/res/layout/activity_rock.xml

Migrated rock list to recycler view

---

app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/Route.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RockViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RouteViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt
app/src/main/res/layout/activity_route.xml
app/src/main/res/layout/list_data_item.xml
app/src/main/res/layout/list_view_content.xml

Migrated route list to recycler view

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/TableActivity.kt
app/src/main/java/com/yacgroup/yacguide/activity_properties/RockSearchable.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RockComment.kt
app/src/main/java/com/yacgroup/yacguide/utils/IntentConstants.kt
app/src/main/res/layout/search_dialog.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Added rock relevance filter

---

app/build.gradle

Drop support for API version <26

---

app/src/main/res/layout/list_data_item.xml

Added ripple effect to list view items

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookAscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/Ascend.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookExporter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/AscentViewAdapter.kt
app/src/main/res/layout/activity_description.xml
app/src/main/res/layout/activity_tourbook.xml
app/src/main/res/layout/activity_tourbook_ascend.xml
app/src/main/res/layout/ascendbar_description.xml
app/src/main/res/layout/button_download.xml
app/src/main/res/layout/choose_tourbook.xml
app/src/main/res/layout/nav_tourbook.xml
app/src/main/res/layout/route_description.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Display ascent list below route description

---

app/build.gradle
app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RegionDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/database/RegionDao.kt
app/src/main/java/com/yacgroup/yacguide/database/SectorDao.kt

Added region dao unit tests

---

app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/TableActivity.kt
app/src/main/java/com/yacgroup/yacguide/activity_properties/RouteSearchable.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RouteComment.kt
app/src/main/java/com/yacgroup/yacguide/utils/IntentConstants.kt
app/src/main/res/layout/route_search_dialog.xml
app/src/main/res/values/strings.xml

Added protection filter for routes

---

app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewItem.kt
app/src/main/res/layout/activity_partners.xml
app/src/main/res/layout/list_data_item_with_buttons.xml

Migrated partner list to recycler view

---

app/build.gradle
app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
app/src/main/java/com/yacgroup/yacguide/network/NetworkTask.kt

Replaced deprecated AsyncTask with coroutine approach

---

app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
app/src/main/java/com/yacgroup/yacguide/PrivacyPolicyActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt
app/src/main/java/com/yacgroup/yacguide/utils/DateUtils.kt
app/src/main/java/com/yacgroup/yacguide/utils/NetworkUtils.kt
app/src/main/java/com/yacgroup/yacguide/utils/ParserUtils.kt

Removed warnings caused by deprecated apis

---

app/build.gradle
app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookAscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookExporter.kt
app/src/main/java/com/yacgroup/yacguide/utils/IntentConstants.kt
app/src/main/res/values/strings.xml

Replaced deprecated onActivityResult with result launchers

---

app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RegionDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RockDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/SectorDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RockComment.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RockCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

Added unit tests for rock database requests

---

.github/workflows/instrumentation-tests.yml
app/build.gradle
app/src/main/AndroidManifest.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
scripts/yacguide/docker.py

* Pump Grade version to v7.4
* Bump Android SDK version to 32

Upgrade Gradle, libraries and Android SDK version

---

app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RegionViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RockCounter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RockCounterConfig.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/SectorViewAdapter.kt
app/src/test/java/com/yacgroup/yacguide/list_adapters/RockCounterTest.kt

Show summary of collected rocks in region view

---

app/src/main/java/com/yacgroup/yacguide/network/CountryParser.kt
app/src/main/java/com/yacgroup/yacguide/network/RegionParser.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt
app/src/main/java/com/yacgroup/yacguide/utils/ParserUtils.kt

Remove unnecessary underscore characters in names

---

app/src/main/java/com/yacgroup/yacguide/BaseNavigationActivity.kt
build.gradle

Fixed a deprecation warning that occurs with this upgrade. See https://developer.android.com/guide/navigation/navigation-custom-back

Upgrade Kotlin version to 1.7.20

---

app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/PartnerDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/Partner.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookExporter.kt

Added partnerDao unit tests

---

app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewItem.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/SwipeController.kt
app/src/main/res/drawable/ic_baseline_sync_24.xml
app/src/main/res/layout/activity_region_manager.xml
app/src/main/res/values/colors.xml

Migrated region manager list to recycler view

---

app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RegionDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RockDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RouteDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/SectorDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RouteComment.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RouteCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

RouteDao unit tests

---

app/src/androidTest/java/com/yacgroup/yacguide/database/AscendDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
app/src/main/java/com/yacgroup/yacguide/database/AscendDao.kt

Added ascendDao unit tests

---

app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/BaseViewItem.kt
app/src/main/res/layout/activity_tourbook.xml

Migrated tourbook list to recycler view

---

app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RegionCommentDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/database/CountryDao.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RegionComment.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RegionCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

Unit tests for RegionCommentDao

---

app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/CountryViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/SwipeController.kt
app/src/main/res/drawable/ic_baseline_push_pin_24.xml
app/src/main/res/drawable/ic_baseline_stroked_pin_24.xml
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml

Pinning approach for country list

---

app/src/androidTest/java/com/yacgroup/yacguide/database/AscendDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/CountryDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/PartnerDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RegionDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RockDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RouteDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/SectorCommentDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/SectorDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/SectorComment.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/SectorCommentDao.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

Added sector comment dao unit tests

---

app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/BaseExporter.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/CsvExporter.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/JsonExporter.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/JsonImporter.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/JsonVerboseExporter.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookExchangeKeys.kt
app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookExporterFactory.kt

Refactor tourbook export

---

app/src/androidTest/java/com/yacgroup/yacguide/database/AscendDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RouteCommentDaoTests.kt

Unit tests for RouteCommentDao

---

app/src/androidTest/java/com/yacgroup/yacguide/database/RegionCommentDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RockCommentDaoTests.kt

Unit tests for RockCommentDao

---

app/src/main/res/drawable/ic_baseline_push_pin_24.xml
app/src/main/res/drawable/ic_baseline_stroked_pin_24.xml

Just a discreet visual improvement

Rotated pin icons by 12 degree

---

app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt
app/src/main/res/drawable/ic_start_done.xml
app/src/main/res/layout/activity_launch.xml

Encircle launch icon after finishing automatic update

---

app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt

Sort downloaded regions to top of list

---

app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt
app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/res/values/setup.xml

This resolves the issue that no countries are shown in start-up which was due to a resources bug.

Fixed incorrect handling with default region id

---

app/src/androidTest/java/com/yacgroup/yacguide/database/RegionDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/DescriptionActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/RegionDao.kt
app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/AscendDiffCallback.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/AscendViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/SectionViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/SectionViewItem.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/TourbookAscendViewAdapter.kt
app/src/main/res/layout/list_view_section_content.xml

Sorry for this huge PR but using nested recycler view seems to be the only way to fix tourbook's inconsistency. And it's the much cleaner approach anyways.
Migration of `RegionManager`'s list will be done in a follow-up PR.
Resolves #382

Migrate tourbook to nested recycler view

---

app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Preparation for the next dev release.

Update Kotlin, Gradle and library versions

---

app/build.gradle
app/src/main/java/com/yacgroup/yacguide/utils/ActivityUtils.kt
app/src/main/res/values/strings.xml

It avoids a hard context switch.

Open URLs in custom tabs, if the browser supports that feature

---

app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt

Fixed invalid ascent colouring in tourbook

---

app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/utils/SearchBarHandler.kt
app/src/main/res/layout/activity_partners.xml
app/src/main/res/layout/searchbar.xml

Add clear text icon to search fields

---

app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/utils/SearchBarHandler.kt
app/src/main/res/layout/searchbar.xml
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml

Enabled sorting-by-name for partners

---

app/src/main/java/com/yacgroup/yacguide/database/tourbook/TourbookEntryVerbose.kt

Include route grade into tour book export

---

app/build.gradle
app/src/main/java/com/yacgroup/yacguide/StatisticsActivity.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/StatisticsViewAdapter.kt
app/src/main/res/layout/expandable_list_item.xml
build.gradle

Enable stacked bar charts for statistics

---

app/src/androidTest/java/com/yacgroup/yacguide/database/AscendDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/StatisticsActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/AscendDao.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/StatisticsViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/utils/ChartFormatter.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/yacgroup/yacguide/utils/ChartFormatterTest.kt

Add ascends-per-year count statistic

---

app/src/androidTest/java/com/yacgroup/yacguide/database/AscendDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/AscendDao.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt

Do not consider botches etc for ascent partner counting

---

app/src/main/java/com/yacgroup/yacguide/StatisticsActivity.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/StatisticsViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/statistics/Statistic.kt
app/src/main/java/com/yacgroup/yacguide/statistics/StatisticGenerator.kt

Preparation-PR of the next statistics to be added

Refactored statistic measurent

---

app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt

Fix tourbook import location restriction

---

app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt

Show rock numbers in search results

---

app/src/main/res/layout/comment.xml

Make links clickable and text selectable inside comment text fields

---

app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/StatisticsActivity.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/StatisticsViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/statistics/StatisticGenerator.kt
app/src/main/java/com/yacgroup/yacguide/statistics/StatisticUtils.kt
app/src/main/res/values/strings.xml

Added ascends-per-partner statistic

---

app/src/main/java/com/yacgroup/yacguide/AscendActivity.kt
app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/res/drawable/ic_baseline_save_24.xml

Improve UI of partners activity

---

app/src/main/res/values/strings.xml

Resolves #473 
Misusing the comment dialog for this by adding another text field yields some problems, so I have decided to simply put it into the according Toast.

Add hint for user to retry update on server error

---

app/src/androidTest/java/com/yacgroup/yacguide/database/AscendDaoTests.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/Common.kt
app/src/androidTest/java/com/yacgroup/yacguide/database/RockDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/StatisticsActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/AscendDao.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RockCounter.kt
app/src/main/java/com/yacgroup/yacguide/statistics/StatisticGenerator.kt
app/src/main/java/com/yacgroup/yacguide/utils/AscendStyle.kt
app/src/main/res/values/strings.xml

Resolves #464 .
To improve performance, this feature has been implemented into one single sql request.

Add new statistic: Newly collected rocks per year

---

app/src/androidTest/java/com/yacgroup/yacguide/database/RegionDaoTests.kt
app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/RegionDao.kt

Delete partners on database reset

---

app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml

Show usage info for certain activities

---

app/src/main/res/values-v35/styles.xml

Opt out edge-to-edge window enforcement introduced with API 35

---

app/src/main/java/com/yacgroup/yacguide/utils/ContactUtils.kt

Fix crash when using contact function for with API>=34
