app/src/main/AndroidManifest.xml
app/src/main/res/xml/network_security_config.xml

Starting with Android 8 HTTP traffic needs to be explicitly allowed.
Fixes #63

Fix networking issues with HTTP traffic on Android >= 8

---

Makefile
app/build.gradle
build.gradle

The following tools/modules are bumped to a higher version:
* Gradle: 3.6.3 -> 4.0.1
* Kotlin: 1.3.60 -> 1.4.10
* com.android.support.constraint:constraint-layout: 1.1.3 -> 2.0.1
* junit:junit: 4.12 -> 4.13
* com.caverock:androidsvg: 1.3 -> 1.4
* io.noties.markwon:core: 4.3.1 -> 4.6.0

Update from API level 28 to 29

---

app/src/main/java/com/yacgroup/yacguide/UpdatableTableActivity.kt
app/src/main/java/com/yacgroup/yacguide/UpdateListener.kt
app/src/main/java/com/yacgroup/yacguide/network/CountryParser.kt
app/src/main/java/com/yacgroup/yacguide/network/JSONWebParser.kt
app/src/main/java/com/yacgroup/yacguide/network/RegionParser.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

Resolves #106.
This also fixes a small bug: If updating a region multiple times without leaving the corresponding activity in between, rock-, route- and comment- data will be downloaded twice the 2nd time, triple the 3rd time etc. - However, this was fixed by introducing an `initNetworkRequests()` method.

Display progress for sector update

---

app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/TourbookExporter.kt
app/src/main/res/values/strings.xml

Fixes #208 
@paetz: What do you say about this solution?
If there is e.g. a syntax issue in the JSON file, the error message looks e.g. like `Unterminated object at character 42 of <JSON string>`. It would be possible to parse this message, cut only the characters around the mentioned position and so show the exact issue. However, I think this may a bit too over-engineered at this point. Additionally the code may break in case the message changes in the future.

Improve error message in case of a tourbook import error

---

app/src/main/java/com/yacgroup/yacguide/ClimbingObject.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/activity_properties/AscentFilterable.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
app/src/main/res/layout/appbar_info_and_map.xml
app/src/main/res/values/strings.xml

Resolves #255 
-> project and botch filters now point to `RouteActivity` to show real projects/botches instead of the according rocks

Show corresponding routes on project or botch filtering

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/RockDao.kt
app/src/main/java/com/yacgroup/yacguide/utils/ParserUtils.kt
docs/release-notes/v0.5.0.md

Accelerated rock search - PLEASE UPDATE YOUR SECTORS

---

app/src/main/java/com/yacgroup/yacguide/RegionActivity.kt
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Highlight downloaded regions

---

app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
app/src/main/res/layout/content_preferences.xml
app/src/main/res/values/strings.xml

Add a reset database button ("Auf Werkseinstellungen zurücksetzen") to the preferences view. After a confirmation dialog it clears the database and tour book and also resets the custom settings to the default values. After deleting a success toast is shown.
For future bugs it might be helpful to give the user the opportunity to reset all databases in the app.
Resolves #242

Add database reset

---

app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt

Routes are not updated by rock but by sector. Since we add only rocks of a certain type to the database, there might be routes whose rock is not present in the db.
Removing `!!` from `getRock(route.parentId)` prevents a crash in that case.

Allow non-existing rock for displaying route

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/utils/SearchBarHandler.kt

Rock and route lists were displayed twice on creating the corresponding activity which doubles the time for time-consuming widgets creation.

Do not re-display rock and route lists on instantiating search bar

---

app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
app/src/main/java/com/yacgroup/yacguide/UpdateHandler.kt
app/src/main/java/com/yacgroup/yacguide/database/CountryDao.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
app/src/main/java/com/yacgroup/yacguide/network/CountryParser.kt
app/src/main/java/com/yacgroup/yacguide/network/RegionParser.kt

Resolves #285 
This PR adds update of country list to the update-all functionality in the region manager.
Note: The fact that updating is asynchronous leads to the (in my eyes) ugly callback implementation where we pass the next element's processing as a callback to the current one's update to be executed after that is finished.
In the future, we might think of refactoring this to Promise pattern.

Updating country list on updating all via region manager

---

app/src/main/java/com/yacgroup/yacguide/SectorActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/Sector.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RegionViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/SectorViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt
app/src/main/res/layout/activity_sector.xml

Migrated sector list to recycler view

---

app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/utils/SearchBarHandler.kt
app/src/main/res/values/setup.xml
app/src/main/res/values/strings.xml

Possibility to set default region

---

app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/activity_properties/RockSearchable.kt
app/src/main/java/com/yacgroup/yacguide/activity_properties/RouteSearchable.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RouteComment.kt
app/src/main/res/layout/route_search_dialog.xml
app/src/main/res/values/strings.xml

Add quality filter for routes

---

app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/TableActivity.kt
app/src/main/java/com/yacgroup/yacguide/activity_properties/RockSearchable.kt
app/src/main/java/com/yacgroup/yacguide/activity_properties/RouteSearchable.kt
app/src/main/java/com/yacgroup/yacguide/database/DatabaseWrapper.kt
app/src/main/java/com/yacgroup/yacguide/database/RouteDao.kt
app/src/main/java/com/yacgroup/yacguide/database/SqlMacros.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RockComment.kt
app/src/main/java/com/yacgroup/yacguide/database/comment/RouteComment.kt
app/src/main/java/com/yacgroup/yacguide/utils/IntentConstants.kt
app/src/main/res/layout/route_search_dialog.xml
app/src/main/res/values/strings.xml

Added drying filter for routes

---

app/src/main/java/com/yacgroup/yacguide/network/JSONWebParser.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

Background:
- When updating a region, the progress info stays at 100% percent for a long time. 
- Reason being, that the SectorParser requests all rocks & routes for a sector at once. Since parsing routes takes much longer than parsing rocks (since there are more), it makes more sense to update the progress info not after parsing rocks but rather after parsing routes.

Made update progress info more accurate

---

app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
app/src/main/java/com/yacgroup/yacguide/UpdateHandler.kt
app/src/main/java/com/yacgroup/yacguide/network/JSONWebParser.kt
app/src/main/res/layout/info_dialog.xml
app/src/main/res/values/strings.xml

Resolves #353 
Note: I've changed the update error handling so that a region update is immediately cancelled if an error occurs. However, for Update-All-Requests, I preserved the handling of continue updating the other regions and omit only the failed one.

Make sector updates cancelable

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/yacgroup/yacguide/AboutActivity.kt
app/src/main/java/com/yacgroup/yacguide/AboutLibrariesActivity.kt
app/src/main/java/com/yacgroup/yacguide/PrivacyPolicyActivity.kt
app/src/main/res/layout/about_entry.xml
app/src/main/res/layout/about_libraries_entry.xml
app/src/main/res/layout/activity_about_libraries.xml
app/src/main/res/values/strings.xml
build.gradle
config/aboutLibraries/libraries/lib_apache_commons_csv.json

Fixes #155 
For some reason, the license for the [Apache Commons CSV](https://commons.apache.org/proper/commons-csv/) library is empty. It is under clarification in issue https://github.com/mikepenz/AboutLibraries/issues/827. Since the information are generated automatically during each build, it should not be a blocker to merge this issue.

Add view that lists all used libraries and their licenses

---

app/src/main/java/com/yacgroup/yacguide/UpdateHandler.kt

For #353 I have accidentally removed the update dialog's behavior that it is always in the foreground even when the user touches outside of it or presses the back button.
I have re-added it in this PR.

Make UpdateDialog always-present again

---

app/src/main/java/com/yacgroup/yacguide/UpdateHandler.kt
app/src/main/java/com/yacgroup/yacguide/network/CountryAndRegionParser.kt
app/src/main/java/com/yacgroup/yacguide/network/JSONWebParser.kt
app/src/main/java/com/yacgroup/yacguide/network/NetworkListener.kt
app/src/main/java/com/yacgroup/yacguide/network/NetworkRequest.kt
app/src/main/java/com/yacgroup/yacguide/network/NetworkTask.kt
app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

Resolves #309
Up to now, json parsing during updating, had been done on the main thread. That's why the percentage display and the abort button were quite slow in response.
The new approach uses a bunch of coroutines (Coroutine = sth. like a lightweight thread):
1. One coroutine per network request pushing its result to a thread-safe queue
2. One coroutine for the worker method that polls and processes this queue
All those are decoupled from the main thread, so that UI works smoothly.

Added queue for network requests

---

app/src/main/java/com/yacgroup/yacguide/network/SectorParser.kt

Show creation date of comments

---

app/src/androidTest/java/com/yacgroup/yacguide/preferences/PreferencesMigrationTests.kt
app/src/main/java/com/yacgroup/yacguide/CountryActivity.kt
app/src/main/java/com/yacgroup/yacguide/LaunchActivity.kt
app/src/main/java/com/yacgroup/yacguide/PartnersActivity.kt
app/src/main/java/com/yacgroup/yacguide/PreferenceFragment.kt
app/src/main/java/com/yacgroup/yacguide/PreferencesActivity.kt
app/src/main/java/com/yacgroup/yacguide/RegionManagerActivity.kt
app/src/main/java/com/yacgroup/yacguide/RockActivity.kt
app/src/main/java/com/yacgroup/yacguide/RouteActivity.kt
app/src/main/java/com/yacgroup/yacguide/TourbookActivity.kt
app/src/main/java/com/yacgroup/yacguide/list_adapters/RockCounterConfig.kt
app/src/main/java/com/yacgroup/yacguide/migration/PreferencesMigration.kt
app/src/main/java/com/yacgroup/yacguide/preferences/PreferencesFormatV2.kt
app/src/main/java/com/yacgroup/yacguide/preferences/PreferencesType.kt
app/src/main/java/com/yacgroup/yacguide/utils/SearchBarHandler.kt
app/src/main/java/com/yacgroup/yacguide/utils/VisualUtils.kt
app/src/main/res/values/setup.xml
app/src/main/res/xml/preferences.xml

* Fixes #453 
* Needs merge of #429 before.

Fix that shared preferences use description strings instead of unique keys

---

app/build.gradle
app/src/main/java/com/yacgroup/yacguide/list_adapters/StatisticsViewAdapter.kt
app/src/main/java/com/yacgroup/yacguide/utils/ChartFormatter.kt
app/src/test/java/com/yacgroup/yacguide/utils/ChartFormatterTest.kt

This PR fixes the issue that we could only have up to 25 axis labels in our statistic graphs.
I have found an actively maintained fork of our chart library that allows configuration of that limit, so I have replaced the original lib by this fork and configured the upper limit of axis labels before displaying it.

Update chart library to be able to configure axis label count
